### PR TITLE
Support Memo Processor's communications mode

### PR DESCRIPTION
**Pull request by classilla**
The Memo Processor cartridge has a communications mode, which serves as a simple dummy terminal program. This works great with an actual CC-40 RS-232 module, but not with HEXTIr. The missing parts are a) support for the `R` option (which looks like an inadvertent oversight) and b) proper 300bps mode since MP only supports 110bps and 300bps, but double speed has issues at 300bps - see https://forum.arduino.cc/t/300-baud-on-uno/371585/4 for a workaround.

This PR fixes both of those problems and works correctly with a real CC-40 using a real MP cartridge. I also threw in some notes about parity, since there are comments in the file about that.

### CODE REVIEW

**Comment by classilla** [comment]
Let me know if you also want me to push my rebuilt firmware binaries (this is just the source).

**Comment by go4retro** [comment]
Thanks!  Yes, if you could include the bins, I will merge the lot.

**Comment by classilla** [comment]
Done.

**Comment by go4retro** [comment]
Thanks!

**Pull request merged**
